---
downloads: ~/.ansible-downloads/

configure_terminal: true
configure_osx: true
configure_zsh: true

# Set to 'true' to configure Visual Studio Code
configure_vscode: true
vscode_extensions:
  - amatiasq.sort-imports
  - arcticicestudio.nord-visual-studio-code
  - dbaeumer.vscode-eslint
  - EditorConfig.EditorConfig
  - esbenp.prettier-vscode
  - formulahendry.auto-rename-tag
  - ms-vscode.vscode-typescript-tslint-plugin
  - ms-vsliveshare.vsliveshare
  - ms-vsliveshare.vsliveshare-audio
  - ms-vsliveshare.vsliveshare-pack
  - nextfaze.json-parse-stringify
  - Perkovec.emoji

configure_ssh_keys: false
ssh_keys:
  - name: id_rsa
    mode: "600"
  - name: id_rsa.pub
    mode: "644"

configure_oh_my_zsh: true
oh_my_zsh_theme: agnoster
oh_my_zsh_plugins:
  - git

configure_nerd_fonts: true
nerd_fonts: 
  - Sauce-Code-Pro

# Set to 'true' to configure the Dock via dockutil.
configure_dock: false
dockitems_remove: []
# - Launchpad
# - TV
# - Podcasts
# - 'App Store'
dockitems_persist: []
# - name: "Sublime Text"
#   path: "/Applications/Sublime Text.app/"
#   pos: 5

configure_sudoers: false
sudoers_custom_config: ''
# Example:
# sudoers_custom_config: |
#   # Allow users in admin group to use sudo with no password.
#   %admin ALL=(ALL) NOPASSWD: ALL

configure_dotfiles: true
dotfiles_files:
  # - .zshrc
  - .gitignore
  - .inputrc
  - .osx
  - .alacritty.yml
  - .yabairc
  - .skhdrc
  - .hammerspoon

configure_config: true
config_files:
  - yabai

configure_clone_repos: true
clone_repos: 
  - repo: https://github.com/AdamWagner/stackline.git
    dest: ~/.hammerspoon/stackline
    
zsh_customizations_repo: https://github.com/talvor/zsh-customizations.git
zsh_customizations_repo_accept_hostkey: true
zsh_customizations_repo_local_destination: ~/.zsh-customizations

homebrew_installed_packages:
  # - ansible # Installed via Pip.
  - git
  - nvm
  - ssh-copy-id
  - cowsay
  - wget
  - zsh-history-substring-search
  - docker-compose
  - "koekeishiya/formulae/yabai"
  - "koekeishiya/formulae/skhd"
  - jq
  - osx-cpu-temp
  - mvnvm

homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - homebrew/cask-fonts

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - chromedriver
  - dropbox
  - firefox
  - gitkraken
  - insomnia
  - atom
  - alacritty
  - visual-studio-code
  - signal
  - veracrypt
  - docker
  - hammerspoon

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps: []
mas_email: ""
mas_password: ""

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
# - name: drush
#   state: present # present/absent, default: present
#   version: "^8.1" # default: N/A
gem_packages: []
# - name: bundler
#   state: present # present/absent/latest, default: present
#   version: "~> 1.15.1" # default: N/A
npm_packages: []
# - name: webpack
#   state: present # present/absent/latest, default: present
#   version: "^2.6" # default: N/A
pip_packages: []
# - name: mkdocs
#   state: present # present/absent/latest, default: present
#   version: "0.16.3" # default: N/A

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
