---
- hosts: all

  vars_files:
    - default.config.yml

  pre_tasks:
    - name: Include playbook configuration.
      include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: ['always']

  roles:
    - role: elliotweiser.osx-command-line-tools
    - role: geerlingguy.mac.homebrew
      tags: ['homebrew']
    - role: geerlingguy.mac.mas
      when: mas_installed_apps or mas_installed_app_ids
      tags: ['mas']
    - role: geerlingguy.mac.dock
      when: configure_dock
      tags: ['dock']

  tasks:
    - import_tasks: tasks/copy_dotfiles.yml
      when: configure_dotfiles
      tags: ['dotfiles']

    - import_tasks: tasks/copy_config.yml
      when: configure_config
      tags: ['config']

    - import_tasks: tasks/zsh-customizations.yml
      when: configure_zsh
      tags: ['zsh-customizations']

    - import_tasks: tasks/vscode.yml
      when: configure_vscode
      tags: ['vscode']

    - import_tasks: tasks/sudoers.yml
      when: configure_sudoers
      tags: ['sudoers']

    - import_tasks: tasks/terminal.yml
      when: configure_terminal
      tags: ['terminal']

    - import_tasks: tasks/osx.yml
      when: configure_osx
      tags: ['osx']

    - import_tasks: tasks/extra-packages.yml
      tags: ['extra-packages']

    - import_tasks: tasks/ssh_keys.yml
      when: configure_ssh_keys
      tags: ['ssh-keys']

    - import_tasks: tasks/oh_my_zsh.yml
      when: configure_oh_my_zsh
      tags: ['oh_my_zsh']

    - import_tasks: tasks/nerd_fonts.yml
      when: configure_nerd_fonts
      tags: ['nerd_fonts']

    - import_tasks: tasks/clone_repos.yml
      when: configure_clone_repos
      tags: ['clone_repos']

    - block:
        - name: Run configured post-provision ansible task files.
          include_tasks: "{{ outer_item }}"
          loop_control:
            loop_var: outer_item
          with_fileglob: "{{ post_provision_tasks|default(omit) }}"
      tags: ['post']
