---
roles:
  - name: elliotweiser.osx-command-line-tools
  - name: geerlingguy.mas
  - name: gantsign.visual-studio-code-extensions
  - name: gantsign.oh-my-zsh

collections:
  - name: geerlingguy.mac
