---
roles:
  - name: elliotweiser.osx-command-line-tools
  - name: geerlingguy.dotfiles
  - name: geerlingguy.mas
  - name: gantsign.visual-studio-code-extensions

collections:
  - name: geerlingguy.mac
